export const data = [
  {
    id: 1,
    title: "텀블러",
    price: "100 P",
    odds: "10%",
    remaining: "3",
    total: "100",
    linkImg: "",
  },
  {
    id: 2,
    title: "기프티콘",
    price: "200 P",
    odds: "10%",
    remaining: "3",
    total: "100",
    linkImg: "",
  },
  {
    id: 3,
    title: "경품3",
    price: "300 P",
    odds: "10%",
    remaining: "3",
    total: "100",
    linkImg: "",
  },
  {
    id: 4,
    title: "경품4",
    price: "500 P",
    odds: "10%",
    remaining: "3",
    total: "100",
    linkImg: "",
  },
  {
    id: 5,
    title: "경품5",
    price: "150 P",
    odds: "10%",
    remaining: "3",
    total: "100",
    linkImg: "",
  },
];
